[package]
name = "mclib-macros"
version = "0.0.1"
license = "Apache-2.0"
description = "Proc-macro for mclib"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = { version = "0.20.3" }
syn = { version = "2.0.39" }
